# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/


# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
services:
    - mysql:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/



test:node_latest:
    image: node:latest
    script:
        - npm install
        - ls
        - npm run coverage


test:node_10:
    image: node:10
    script:
        - npm install
        - ls
        - npm run test
