# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/


# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
services:
    - mariadb:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

variables:
    MYSQL_DATABASE: "test"
    MYSQL_ROOT_PASSWORD: "PYHjnKBBDl"

test:node_latest:
    image: node:latest
    script:
        - npm install
        - echo "$COVERALLS_REPO_TOKEN"
        - npm run coverage


test:node_10:
    image: node:10
    script:
        - npm install
        - npm run test

test:node_11:
    image: node:11
    script:
        - npm install
        - npm run test
    only:
        - tags

test:node_12:
    image: node:12
    script:
        - npm install
        - npm run test
    only:
        - tags

test:node_13:
    image: node:13
    script:
        - npm install
        - npm run test
    only:
        - tags

test:node_14:
    image: node:14
    script:
        - npm install
        - npm run test
    only:
        - tags

test:node_15:
    image: node:15
    script:
        - npm install
        - npm run test
    only:
        - tags

